"""second commit

Revision ID: 909e52ee27d6
Revises: d32d2b101480
Create Date: 2020-10-08 17:15:47.105793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909e52ee27d6'
down_revision = 'd32d2b101480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
